<<<<<<< HEAD
services:
  - type: web
    name: reading-room-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
=======
services:
  - type: web
    name: reading-room-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
>>>>>>> 42116c6 (Initial commit)
